pool:
  name: Default

trigger:
  branches:
    include:
      - 'main'

variables:
  - name: workingDirectory
    value: apps/shell

steps:
  - script: npm ci
    displayName: Install

  - script: npm run nx build shell
    displayName: Build
    workingDirectory: $(workingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish dist folder
    inputs:
      PathtoPublish: $(workingDirectory)/dist
      ArtifactName: 'dist'
      publishLocation: 'Container'
