services:
  proxy:
    build: ./proxy
    ports:
      - '4500:80'
  shell:
    build: ../apps/shell
    container_name: shell
    ports:
      - '80'
    volumes:
      - type: bind
        source: ./modules.json
        target: /usr/share/nginx/html/assets/modules.json
  login:
    build: ../apps/login
    container_name: login
    ports:
      - '80'
