name: App Login CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'

      - name: Build
        run: npx nx build login --configuration production

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: apps/login/dist/

  staging:
    needs:
      - build
    environment:
      name: netlify-staging
      url: ${{ steps.deploy_netlify.outputs.deploy-url }}
    runs-on: ubuntu-latest
    name: Deploy to staging
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: apps/login/dist

      - name: Deploy to Netlify
        id: deploy_netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './apps/login/dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.LOGIN_NETLIFY_SITE_ID }}
