name: App Shell CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: npx nx build shell --configuration production

      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: apps/shell/dist/

  deploy:
    needs:
      - build
    environment:
      name: netlify
      url: https://ng-microfrontends.netlify.app
    runs-on: ubuntu-latest
    name: Deploy to Netlify
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: apps/shell/dist

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './apps/shell/dist'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SHELL_NETLIFY_SITE_ID }}
