name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # https://github.com/nrwl/nx-set-shas
    steps:
      - uses: actions/checkout@v2
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'

      - name: Install
        run: npm i

      - name: Build
        run: npx nx affected --target=build --parallel --max-parallel=3

      - name: Test
        run: npx nx affected --target=test --parallel --max-parallel=2

